name: Run News Scraper Automatically

on:
  schedule:
    - cron: "0 19 * * *"  # Runs every day at 7:00 PM UTC (12:00 AM PST)
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure all dependencies are listed in this file

      - name: Run Scraper
        run: python run_spiders.py
